package com.huangjiang.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DTRANSFER_DETAIL".
 */
public class TransferDetail {

    private Long id;
    private Long totalSize;

    public TransferDetail() {
    }

    public TransferDetail(Long id) {
        this.id = id;
    }

    public TransferDetail(Long id, Long totalSize) {
        this.id = id;
        this.totalSize = totalSize;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

}
